print("Hej från Joakim!")
print("Hej från David!")
print("Hej från Rufus!")
print("Hej från Emil!")
print("Hej från Aleks!")
print("Hej från Benjamin!")
print("hej från Alfred")
print("Hej från Elton!")
print("Hej från Casper!")
print("Hej från Benjamin K")
print("Hej från Otto!")
print("Hej från Tina")
print("Hello Malin")
print("Hello from Jens")
print("Hello from Elias")
print("Hello from Emanuel")
print("Hello from Filip")
print("Hello from Zineb!!")
